apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: demonstrator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-app
        image: nodejs-app:v1.0.0
        ports:
        - containerPort: 3000
