apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: demonstrator
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 35000  
      targetPort: 3000
  type: NodePort
