apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  ports:
    - protocol: TCP
      name: jenkins-ui
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: jenkins-service
      port: 50000
      targetPort: 50000
  type: NodePort
  selector:
    app: jenkins